# This is a TOML document to configure your Wundergraph workspaces.
# For more information, see https://docs.wundergraph.com/docs/cloud/configuration

version = 1

[[projects]]
name = "project-a" # The name of cloud project
workspace = "/project-a"

[[projects]]
name = "project-b"
workspace = "/project-b"